class TestData:
    PAGE_TITLE = "My Store"
    PAGE_ACCOUNT_TITLE = "My account - My Store"
    BASE_URL = "https://automationpractice.com/index.php"
    EMAIL= "dothanhha10@yopmail.com"
    EMAIL_F = "testabc"
    CUSTOMER_FIRST_NAME = "Angela"
    CUSTOMER_LAST_NAME = "Testabc"
    PASSWORD = "Test@12345"
    ADDRESS = "15, 72 lane, ABC street, XYZ district, Hanoi"
    CITY = "Hanoi"
    ID_STATE = "Alabama"
    POSTCODE = "12345"
    ID_COUNTRY = "United States"
    PHONE_MOBILE = "0912351258"
